const assert = require('node:assert/strict');

module.exports = async ({ request, login, student, staff, admin, fixtures }) => {
  let checks = 0;
  const endpoint = '/api/admin_workspace.php';
  await request(endpoint + '?view=overview', null, undefined, { status: 401 });
  await request(endpoint + '?view=overview', student, undefined, { status: 403 });
  await request(endpoint + '?view=staff', staff, undefined, { status: 403 });
  await request(endpoint + '?view[]=staff', admin, undefined, { status: 400 });
  await request(endpoint, admin, { action: 'create_staff' }, { headers: { 'X-CSRF-Token': 'bad' }, status: 403 });
  await request(endpoint, admin, { action: 'create_staff', first_name: [] }, { status: 400 });
  const details = { first_name: 'New', last_name: '<Staff>', email: 'newstaff@example.test', office_id: 2, password: 'regression-password', is_active: true };
  await request(endpoint, admin, { ...details, action: 'create_staff', password: 'short' }, { status: 400 });
  await request(endpoint, admin, { ...details, action: 'create_staff', office_id: [] }, { status: 400 });
  await request(endpoint, admin, { ...details, action: 'create_staff', office_id: 99999 }, { status: 400 });
  const created = await request(endpoint, admin, { ...details, action: 'create_staff' });
  const account = await login('newstaff');
  const staffData = await request(endpoint + '?view=staff', admin);
  assert.equal(staffData.items.find(row => Number(row.user_id) === created.user_id).last_name, '<Staff>');
  assert.ok(staffData.items.every(row => !('password_hash' in row) && !('password' in row)));
  checks += 2;
  await request(endpoint, admin, { ...details, action: 'create_staff' }, { status: 409 });
  await request(endpoint, admin, { ...details, action: 'update_staff', user_id: fixtures.student }, { status: 404 });
  await request(endpoint, admin, { action: 'delete_staff', user_id: fixtures.admin }, { status: 404 });
  await request(endpoint, admin, { action: 'delete_staff', user_id: fixtures.student }, { status: 404 });
  await request(endpoint, admin, { action: 'assign_concern', inquiry_id: fixtures.otherInquiry, staff_id: fixtures.staff }, { status: 409 });
  await request(endpoint, admin, { action: 'assign_concern', inquiry_id: 99999, staff_id: created.user_id }, { status: 404 });
  await request(endpoint, admin, { action: 'assign_concern', inquiry_id: fixtures.otherInquiry, staff_id: created.user_id });
  let detail = await request(endpoint + '?view=concern&inquiry_id=' + fixtures.otherInquiry, admin);
  assert.equal(Number(detail.item.assigned_staff_id), created.user_id);
  assert.equal(detail.item.status, 'In Progress');
  const inbox = await request('/api/notifications.php', account);
  assert.ok(inbox.items.some(item => item.title === 'Concern assigned to you'));
  checks += 3;
  await request('/api/staff_action.php', account, { action: 'respond', inquiry_id: fixtures.otherInquiry, message: 'Historical staff reply' });
  await request(endpoint, admin, { ...details, action: 'update_staff', user_id: created.user_id, office_id: 1, password: '' });
  detail = await request(endpoint + '?view=concern&inquiry_id=' + fixtures.otherInquiry, admin);
  assert.equal(detail.item.assigned_staff_id, null, 'Office changes must release old assignments.'); checks++;
  await request(endpoint, admin, { ...details, action: 'update_staff', user_id: created.user_id, password: '', is_active: false });
  await request('/api/get_inquiries.php', account, undefined, { status: 401 });
  await request(endpoint, admin, { action: 'assign_concern', inquiry_id: fixtures.otherInquiry, staff_id: created.user_id }, { status: 409 });
  await request(endpoint, admin, { ...details, action: 'update_staff', user_id: created.user_id, password: '' });
  await request(endpoint, admin, { action: 'assign_concern', inquiry_id: fixtures.otherInquiry, staff_id: created.user_id });
  await request(endpoint, admin, { action: 'delete_staff', user_id: created.user_id });
  await request(endpoint, admin, { action: 'delete_staff', user_id: created.user_id }, { status: 404 });
  await request('/api/admin_action.php', admin, { action: 'toggle_user_status', user_id: created.user_id }, { status: 404 });
  detail = await request(endpoint + '?view=concern&inquiry_id=' + fixtures.otherInquiry, admin);
  assert.equal(detail.item.assigned_staff_id, null);
  assert.ok(detail.item.replies.some(reply => reply.message === 'Historical staff reply' && reply.staff_name === 'New <Staff>'));
  assert.ok(!(await request(endpoint + '?view=staff', admin)).items.some(row => Number(row.user_id) === created.user_id));
  checks += 3;
  await request('/api/staff_action.php', staff, { action: 'update_status', inquiry_id: fixtures.inquiry, status: 'Resolved' });
  await request(endpoint, admin, { action: 'assign_concern', inquiry_id: fixtures.inquiry, staff_id: fixtures.staff }, { status: 409 });
  const kb = { title: '<Enrollment> registration', content: 'Enrollment registration requires the approved application.', status: 'Draft', office_id: '' };
  await request(endpoint, admin, { ...kb, action: 'create_knowledge', content: [] }, { status: 400 });
  await request(endpoint, admin, { ...kb, action: 'create_knowledge', status: 'Invalid' }, { status: 400 });
  await request(endpoint, admin, { ...kb, action: 'create_knowledge', content: 'x'.repeat(6001) }, { status: 400 });
  const entry = await request(endpoint, admin, { ...kb, action: 'create_knowledge' });
  await request(endpoint, admin, { ...kb, action: 'update_knowledge', entry_id: entry.entry_id, status: 'Published', office_id: 1 });
  assert.equal((await request(endpoint + '?view=knowledge', admin)).items.find(row => Number(row.entry_id) === entry.entry_id).status, 'Published'); checks++;
  await request(endpoint, staff, { action: 'delete_knowledge', entry_id: entry.entry_id }, { status: 403 });
  await request(endpoint, admin, { action: 'delete_knowledge', entry_id: entry.entry_id });
  await request(endpoint, admin, { action: 'delete_knowledge', entry_id: entry.entry_id }, { status: 404 });
  await request(endpoint + '?view=concerns&status[]=Pending', admin, undefined, { status: 400 });
  const unassigned = await request(endpoint + '?view=concerns&assignment=unassigned', admin);
  assert.ok(unassigned.items.every(item => item.assigned_staff_id === null && item.status !== 'Resolved')); checks++;
  assert.ok((await request(endpoint + '?view=concerns&office_id=2', admin)).items.every(item => Number(item.office_id) === 2)); checks++;
  const overview = await request(endpoint + '?view=overview', admin);
  assert.ok(overview.stats.total >= 2 && overview.stats.inquiries >= 2); checks++;
  const query = '?type=concerns&from=2000-01-01&to=2099-12-31';
  await request('/api/admin_report.php' + query, null, undefined, { status: 401 });
  await request('/api/admin_report.php' + query, student, undefined, { status: 403 });
  await request('/api/admin_report.php?type=concerns&from=2026-02-30&to=2026-03-01', admin, undefined, { status: 400 });
  await request('/api/admin_report.php?type=concerns&from=2026-04-01&to=2026-03-01', admin, undefined, { status: 400 });
  await request('/api/admin_report.php?type[]=concerns&from=2026-01-01&to=2026-12-31', admin, undefined, { status: 400 });
  const report = await request('/api/admin_report.php' + query, admin);
  assert.ok(report.total >= 2 && report.headers.includes('Assigned Staff'));
  assert.ok(report.rows.every(row => row.length === report.headers.length)); checks += 2;
  const csv = await request('/api/admin_report.php' + query + '&format=csv', admin);
  assert.match(csv.response.headers.get('content-disposition'), /attachment; filename="helpdesk-concerns/);
  assert.match(csv.text, /Concern ID/); assert.match(csv.text, new RegExp('INQ-' + fixtures.otherInquiry)); checks += 2;
  const print = await request('/api/admin_report.php' + query + '&format=print', admin);
  assert.match(print.text, /window.print/); assert.ok(!print.text.includes('password_hash')); checks++;
  const chats = await request('/api/admin_report.php?type=inquiries&from=2000-01-01&to=2099-12-31&category=Registrar', admin);
  assert.ok(chats.total >= 2);
  assert.ok(chats.rows.every(row => row[3] === 'Registrar'));
  assert.ok(!JSON.stringify(chats).includes('separate Registrar conversation')); checks += 2;
  const html = await request('/dashboard_admin.php', admin);
  assert.match(html.text, /id="staffForm"/); assert.match(html.text, /id="reportForm"/); assert.match(html.text, /id="assignmentForm"/);
  assert.ok(!html.text.includes('Blank slate'));
  checks++;
  checks += await require('./admin_ui_regression.cjs')(html.text);
  console.log('Admin HTTP assertion checks passed: ' + checks);
  return checks;
};
