const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');

module.exports = async ({ homeHtml, profileHtml, registeredHtml }) => {
  let checks = 0;
  const check = (condition, message) => { assert.ok(condition, message); checks++; };
  const home = new JSDOM(homeHtml);
  const profile = new JSDOM(profileHtml, { url: 'http://helpdesk.test/student_profile.php', runScripts: 'outside-only', pretendToBeVisual: true });
  const registered = new JSDOM(registeredHtml, { url: 'http://helpdesk.test/student_profile.php', runScripts: 'outside-only' });
  const normalizeSidebar = document => {
    const sidebar = document.querySelector('.sidebar').cloneNode(true);
    sidebar.querySelectorAll('.nav-item').forEach(node => node.classList.remove('active'));
    sidebar.querySelectorAll('.time').forEach(node => { node.textContent = ''; });
    return sidebar.outerHTML;
  };
  const sources = file => fs.readFileSync(path.resolve(__dirname, '../public/assets/js', file), 'utf8');
  const turn = () => new Promise(resolve => setTimeout(resolve, 10));
  try {
    const { window } = profile;
    const { document } = window;
    const $ = id => document.getElementById(id);
    check(normalizeSidebar(home.window.document) === normalizeSidebar(document), 'Profile replaced the dashboard sidebar markup.');
    check(!document.querySelector('.workspace-sidebar,.workspace-header'), 'Profile introduced a different workspace shell.');
    check(home.window.document.querySelector('#chatHistoryPanel').outerHTML === $('chatHistoryPanel').outerHTML, 'Profile replaced the dashboard history panel.');
    const styles = document.querySelectorAll('link[rel=stylesheet]');
    check([...styles].map(node => node.getAttribute('href')).join() === [...home.window.document.querySelectorAll('link[rel=stylesheet]')].map(node => node.getAttribute('href')).join(), 'Profile changed the dashboard CSS bundle.');
    check($('profileView').style.display === 'block' && $('heroView').style.display === 'none', 'Direct profile navigation did not open Profile.');
    check($('navProfile').classList.contains('active') && !$('navAskBen').classList.contains('active'), 'Direct profile navigation highlighted the wrong item.');
    const form = document.querySelector('#profileView form');
    check(form.getAttribute('action') === 'student_profile.php' && form.querySelector('[name=_csrf_token]'), 'Profile submissions lost their endpoint or CSRF token.');
    check(document.querySelector('.profile-identity h2') && document.querySelector('.profile-edit-link'), 'Profile is missing its student identity or edit action.');
    check(!document.querySelector('#profileView .account-state,.profile-status'), 'Profile still displays an approval notice.');
    check([...document.querySelectorAll('.profile-detail-section h2')].map(node => node.textContent).join() === 'Personal details,Academic details,Contact details', 'Profile fields are not grouped by purpose.');
    check(document.querySelector('.profile-history')?.tagName === 'DETAILS' && !document.querySelector('.profile-history').open, 'Account history is not a collapsed disclosure.');
    const sidebar = document.querySelector('.sidebar');
    const history = $('chatHistoryPanel');
    const notificationBar = document.querySelector('.student-notification-bar');
    window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
    window.HTMLDialogElement.prototype.close = function (value) { this.returnValue = value; this.removeAttribute('open'); this.dispatchEvent(new window.Event('close')); };
    let fetchGate;
    window.fetch = async () => fetchGate ? fetchGate : ({ ok: true, json: async () => ({ success: true, concerns: [{ inquiry_id: 7, subject: 'Profile test concern', description: 'Details', status: 'On Hold', office: 'Registrar', replies: [], created_at: '2026-10-05 10:00:00' }] }) });
    window.eval(sources('ben_chat.js') + '\nwindow.BenChatUI = BenChatUI;');
    for (const script of document.querySelectorAll('script:not([src])')) window.eval(script.textContent);
    window.eval(sources('student_account_actions.js'));
    window.eval(sources('student_profile.js'));
    await turn();
    const mobile = form.elements.mobile_number;
    const save = form.querySelector('[data-contact-save]');
    const reset = form.querySelector('[data-contact-reset]');
    const original = mobile.value;
    check(save.disabled && reset.hidden, 'Unchanged contact details offer an unnecessary save/reset.');
    mobile.value = '09123456789';
    mobile.dispatchEvent(new window.Event('input', { bubbles: true }));
    check(!save.disabled && !reset.hidden, 'Editing a phone number did not enable its actions.');
    reset.click();
    check(mobile.value === original && save.disabled && reset.hidden && document.activeElement === mobile, 'Discarding contact changes did not restore the original value and focus.');
    $('navAskBen').click();
    check($('heroView').style.display === 'block' && $('profileView').style.display === 'none', 'Profile cannot return to Ask Ben.');
    $('navProfile').click();
    check($('profileView').style.display === 'block' && $('heroView').style.display === 'none', 'Profile click did not switch content in place.');
    check(document.querySelector('.sidebar') === sidebar && $('chatHistoryPanel') === history && document.querySelector('.student-notification-bar') === notificationBar, 'Profile navigation recreated the dashboard frame.');
    $('navMyConcerns').click(); await turn();
    check($('concernsView').style.display === 'block' && $('profileView').style.display === 'none', 'Concerns overlaps Profile.');
    $('navProfile').click();
    await window.showChatView('General');
    check($('chatView').classList.contains('active') && $('profileView').style.display === 'none', 'Ben chat overlaps Profile.');
    $('navProfile').click();
    check(!$('chatView').classList.contains('active'), 'Profile failed to close Ben chat.');
    await window.openThreadView(7);
    check($('threadView').style.display === 'flex' && $('profileView').style.display === 'none', 'Staff thread overlaps Profile.');
    let resolve;
    fetchGate = new Promise(done => { resolve = done; });
    const loading = window.openThreadView(7);
    $('navProfile').click();
    resolve({ ok: true, json: async () => ({ success: true, concerns: [] }) });
    await loading;
    check($('profileView').style.display === 'block' && $('threadView').style.display === 'none', 'A delayed staff thread reopened over Profile.');
    document.querySelector('.student-logout-link').click();
    check($('actionConfirmDialog').open && $('actionConfirmTitle').textContent === 'Log out?', 'Profile lost the original student logout confirmation.');
    $('actionConfirmCancel').click(); await turn();
    check(!$('actionConfirmDialog').open, 'Student logout cannot be cancelled.');
    mobile.value = '09123456789';
    mobile.dispatchEvent(new window.Event('input', { bubbles: true }));
    const submit = new window.Event('submit', { bubbles: true, cancelable: true });
    form.dispatchEvent(submit);
    check(!submit.defaultPrevented && save.disabled && reset.disabled && form.getAttribute('aria-busy') === 'true' && save.textContent.includes('Saving...'), 'Contact saving is missing its busy state.');
    const duplicate = new window.Event('submit', { bubbles: true, cancelable: true });
    form.dispatchEvent(duplicate);
    check(duplicate.defaultPrevented, 'Contact saving permits duplicate submissions.');
    window.dispatchEvent(new window.Event('pageshow'));
    check(!save.disabled && !reset.disabled && !form.hasAttribute('aria-busy') && save.textContent.includes('Save contact'), 'Returning with browser Back left contact editing stuck in its saving state.');
    const registeredDocument = registered.window.document;
    check(registeredDocument.querySelector('.sidebar .brand-name').textContent === 'HelpdeskCRMC' && registeredDocument.querySelector('#navProfile.active'), 'Registered profile changed the original branding/navigation.');
    check(registeredDocument.querySelector('#navAskBen').getAttribute('href') === 'dashboard_student.php' && !registeredDocument.querySelector('#navAskBen').hasAttribute('aria-disabled'), 'New student dashboard navigation is still gated.');
    check(registeredDocument.querySelector('#chatView') && registeredDocument.querySelector('#chatHistoryPanel') && registeredDocument.querySelector('.notification-center'), 'New student is missing service views.');
    registered.window.HTMLDialogElement.prototype.showModal = window.HTMLDialogElement.prototype.showModal;
    registered.window.HTMLDialogElement.prototype.close = function (value) { this.returnValue = value; this.removeAttribute('open'); this.dispatchEvent(new registered.window.Event('close')); };
    registered.window.eval(sources('student_account_actions.js'));
    registeredDocument.querySelector('.student-logout-link').click();
    check(registeredDocument.getElementById('actionConfirmDialog').open, 'Registered profile lost student logout confirmation.');
    registeredDocument.getElementById('actionConfirmCancel').click(); await turn();
  } finally { home.window.close(); profile.window.close(); registered.window.close(); }
  console.log('Original student profile UI assertions passed: ' + checks);
  return checks;
};
