const assert = require('node:assert/strict');

module.exports = async ({ request, student, staff, admin, fixtures }) => {
  let checks = 0;
  const uiPages = {};
  for (const name of ['student_accounts.php', 'school_catalog.php']) {
    await request('/' + name, student, undefined, { status: 302 });
    await request('/' + name, staff, undefined, { status: 302 });
    const response = await request('/' + name, admin);
    uiPages[name] = response.text;
    assert.ok(!response.text.includes('password_hash'));
    checks++;
  }
  const page = await request('/register.php', null);
  uiPages['register.php'] = page.text;
  uiPages['student_privacy.php'] = (await request('/student_privacy.php', null)).text;
  uiPages['terms.php'] = (await request('/terms.php', null)).text;
  uiPages['dashboard_admin.php'] = (await request('/dashboard_admin.php', admin)).text;
  uiPages['dashboard_student.php'] = (await request('/dashboard_student.php', student)).text;
  uiPages['student_profile.php?fixture=1'] = (await request('/student_profile.php', student)).text;
  uiPages['student_profile.php?edit=1'] = (await request('/student_profile.php?edit=1', student)).text;
  assert.match(page.text, /Student ID number/);
  assert.match(page.text, /name="terms_accepted"/);
  assert.match(page.text, /name="privacy_accepted"/);
  assert.match(uiPages['student_privacy.php'], /Republic Act No\. 10173/);
  assert.ok(!uiPages['student_accounts.php'].includes('School record review') && !uiPages['student_accounts.php'].includes('Review status'));
  checks += 5;
  const cookie = page.response.headers.getSetCookie()[0].split(';')[0];
  const token = page.text.match(/name="_csrf_token" value="([^"]+)"/)[1];
  const details = { ...fixtures.academic, first_name: 'HTTP', last_name: '<Student>', middle_name: 'Middle',
    student_number: 'HTTP-REG-0001', email: 'http.registration@example.test', password: 'http-registration-test', confirm_password: 'http-registration-test' };
  const anonymous = { cookie, token };
  const before = (await request('/student_accounts.php?search=HTTP-REG-0001', admin)).text;
  assert.match(before, /No student accounts match/); checks++;
  for (const field of ['terms_accepted', 'privacy_accepted']) {
    const missing = { ...details, _csrf_token: token };
    delete missing[field];
    const refused = await request('/register.php', anonymous, new URLSearchParams(missing));
    assert.match(refused.text, /You must/); checks++;
    const bypass = new URLSearchParams({ ...details, _csrf_token: token });
    bypass.delete(field); bypass.set(field + '[]', '1');
    assert.match((await request('/register.php', anonymous, bypass)).text, /You must/); checks++;
  }
  assert.match((await request('/student_accounts.php?search=HTTP-REG-0001', admin)).text, /No student accounts match/); checks++;
  const stale = await request('/register.php', anonymous, new URLSearchParams({ ...details, terms_version: 'old', _csrf_token: token }));
  assert.match(stale.text, /legal documents have changed/);
  assert.ok(!/name="(?:terms|privacy)_accepted"[^>]* checked/.test(stale.text)); checks += 2;
  const badCsrf = await request('/register.php', anonymous, new URLSearchParams({ ...details, _csrf_token: 'bad' }));
  assert.match(badCsrf.text, /Invalid or expired/); checks++;
  const invalid = await request('/register.php', anonymous, new URLSearchParams({ ...details, college_id: '99999', _csrf_token: token }));
  assert.match(invalid.text, /available program belonging to your college/); checks++;
  const registered = await request('/register.php', anonymous, new URLSearchParams({ ...details, role: 'admin', _csrf_token: token }), { status: 302 });
  assert.equal(registered.response.headers.get('Location'), 'dashboard_student.php'); checks++;
  const newStudent = { cookie: registered.response.headers.getSetCookie()[0].split(';')[0], token };
  const dashboard = await request('/dashboard_student.php', newStudent);
  assert.match(dashboard.text, /id="heroView"/);
  const profile = await request('/student_profile.php?user_id=' + fixtures.student, newStudent);
  uiPages['student_profile.php'] = profile.text;
  assert.match(profile.text, /HTTP &lt;Student&gt;/);
  assert.ok(!profile.text.includes('TEST-student') && !profile.text.includes('password_hash'));
  assert.ok(!profile.text.includes('Awaiting school review') && !profile.text.includes('Student account approved'));
  checks += 4;
  for (const endpoint of ['get_inquiries.php', 'list_chat_sessions.php', 'notifications.php']) await request('/api/' + endpoint, newStudent);
  const savedChat = await request('/api/save_chat_session.php', newStudent, { category: 'General', session_key: 'b'.repeat(32), conversationHistory: [] });
  assert.equal(savedChat.success, true); checks++;
  await request('/api/ai_chat.php', newStudent, { message: [] }, { status: 400 });
  await request('/api/upload_file.php', newStudent, {}, { status: 400 });
  await request('/student_accounts.php', newStudent, undefined, { status: 302 });
  const students = await request('/student_accounts.php?search=HTTP-REG-0001', admin);
  const id = students.text.match(/href="student_accounts\.php\?user_id=(\d+)"/)[1];
  const account = await request('/student_accounts.php?user_id=' + id, admin);
  assert.match(account.text, /Terms version accepted/);
  assert.match(account.text, /Privacy consent recorded at/);
  assert.ok(!account.text.includes('Applicant identity confirmed') && !account.text.includes('Save review')); checks += 3;
  await request('/student_accounts.php', admin, new URLSearchParams({ _csrf_token: admin.token, user_id: id, action: 'review' }), { status: 400 });
  const update = await request('/student_profile.php', newStudent, new URLSearchParams({ ...details, user_id: fixtures.student, section: 'BSIT-2C', action: 'update', _csrf_token: token }), { status: 302 });
  assert.equal(update.response.headers.get('Location'), 'student_profile.php'); checks++;
  assert.match((await request('/student_profile.php', newStudent)).text, /BSIT-2C/); checks++;
  assert.ok(!(await request('/student_profile.php', student)).text.includes('BSIT-2C')); checks++;
  const contactCsrf = await request('/student_profile.php', student, new URLSearchParams({ action: 'contact', _csrf_token: 'bad', mobile_number: '12345678' }));
  assert.match(contactCsrf.text, /Invalid or expired/); checks++;
  await request('/student_profile.php', student, new URLSearchParams({ action: 'contact', _csrf_token: student.token, mobile_number: '09123456789' }), { status: 302 });
  const contactReloaded = await request('/student_profile.php', student);
  assert.match(contactReloaded.text, /Your mobile number was updated/);
  assert.match(contactReloaded.text, /value="09123456789"/); checks += 2;
  const access = { _csrf_token: admin.token, action: 'access', user_id: id, is_active: '0', reason: 'Temporary suspension.' };
  await request('/student_accounts.php', staff, new URLSearchParams(access), { status: 302 });
  await request('/student_accounts.php', admin, new URLSearchParams(access), { status: 302 });
  await request('/api/list_chat_sessions.php', newStudent, undefined, { status: 401 });
  checks += await require('./student_profile_ui_regression.cjs')({ homeHtml: uiPages['dashboard_student.php'], profileHtml: uiPages['student_profile.php?fixture=1'], registeredHtml: uiPages['student_profile.php'] });
  checks += require('./workspace_ui_regression.cjs')({ pages: uiPages, registrationFixture: details });
  checks += await require('./profile_visual_regression.cjs')({ pages: uiPages, baseUrl: page.response.url });
  checks += await require('./registration_visual_regression.cjs')({ pages: uiPages, baseUrl: page.response.url, fixture: details });
  console.log('Student account HTTP assertions passed: ' + checks);
  return checks;
};
