<?php

// Shared controls are loaded once by the page's main bundle.
$workspaceStyles = [
    'shared/tokens.css',
    'shared/base.css',
    'shared/controls.css',
    'shared/forms.css',
    'shared/dialogs.css',
    'shared/workspace.css',
];

return [
    'workspace_ui' => $workspaceStyles,
    'workspace_tables' => ['admin/tables.css'],
    'login' => [
        'login.css',
    ],
    'dashboard_student' => [
        'shared/tokens.css',
        'student/base.css',
        'student/sidebar.css',
        'student/home.css',
        'student/history-panel.css',
        'student/concerns-list.css',
        'student/ben-dialog.css',
        'student/chat-header.css',
        'student/chat-messages.css',
        'student/chat-actions.css',
        'student/chat-composer.css',
        'student/chat-history.css',
        'student/thread-header.css',
        'student/thread-messages.css',
        'student/thread-reply.css',
        'student/thread-feedback.css',
        'student/dialogs.css',
        'student/concern-cards.css',
        'student/concern-replies.css',
        'student/concern-forms.css',
        'student/concern-states.css',
        'student/profile.css',
        'student/profile-form.css',
        'student/responsive.css',
        'notifications.css',
        'components/escalation-base.css',
        'components/escalation-form.css',
    ],
    'dashboard_staff' => [
        'shared/tokens.css',
        'staff/base.css',
        'staff/sidebar.css',
        'staff/header.css',
        'staff/queue.css',
        'staff/detail.css',
        'staff/thread.css',
        'staff/reply.css',
        'staff/responsive-base.css',
        'staff/dialogs.css',
        'staff/workspace-layout.css',
        'staff/workspace-queue.css',
        'staff/workspace-detail.css',
        'staff/workspace-reply.css',
        'staff/mobile-controls.css',
        'staff/responsive-tablet.css',
        'staff/responsive-mobile.css',
        'notifications.css',
    ],
    'dashboard_admin' => [
        ...$workspaceStyles,
        'admin/layout.css',
        'admin/overview.css',
        'admin/tables.css',
        'admin/knowledge.css',
        'admin/reports.css',
        'admin/dialogs-forms.css',
        'admin/concern-thread.css',
        'admin/toast.css',
        'admin/responsive.css',
        'notifications.css',
    ],
    'landing' => [
        'landing/base.css',
        'landing/navigation.css',
        'landing/hero.css',
        'landing/chat-preview.css',
        'landing/offices.css',
        'landing/sections.css',
        'landing/contact.css',
        'landing/footer.css',
        'landing/responsive.css',
    ],
    'student_accounts' => [
        'accounts/layout.css',
        'accounts/profile-form.css',
        'accounts/states.css',
        'accounts/details.css',
        'accounts/catalog.css',
        'accounts/registration.css',
        'accounts/privacy.css',
        'accounts/responsive.css',
    ],
];
